[target.aarch64-linux-android]
ar = "C:/Users/u7541/AppData/Local/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
linker = "C:/Users/u7541/AppData/Local/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android33-clang++.cmd"