[target.aarch64-linux-android]
linker = "C:/Users/u7541/AppData/Local/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android21-clang.cmd"
ar = "C:/Users/u7541/AppData/Local/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"

[target.armv7-linux-androideabi]
linker = "C:/Users/u7541/AppData/Local/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi21-clang.cmd"
ar = "C:/Users/u7541/AppData/Local/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"

[target.i686-linux-android]
linker = "C:/Users/u7541/AppData/Local/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/windows-x86_64/bin/i686-linux-android21-clang.cmd"
ar = "C:/Users/u7541/AppData/Local/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"

[target.x86_64-linux-android]
linker = "C:/Users/u7541/AppData/Local/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android21-clang.cmd"
ar = "C:/Users/u7541/AppData/Local/Android/Sdk/ndk/28.0.12674087/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"